### ISSUE TITLE
文章列表的评论数好像不对，没有加上里面的评论。

### ISSUE THREAD

**Issue by halfrost** [dgytdhy/dgytdhy.github.com#9]
![image](https://cloud.githubusercontent.com/assets/10825609/25930236/b12707a6-3637-11e7-811f-a1936cd708d6.png)

如上图。估计瓜神1分钟就把这个issue秒杀了。

**Comment by Desgard** [comment]
是啊。。因为 gitment 还没有提供获取指定 issue comment 数量的 API。我感觉我要自己增加这个API来搞。

**Comment by halfrost** [comment]
瓜神稳的。。肯定搞的定的。。。😘😘
